#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${DIR}/shared"

echo_headline "Building project"
ng build --prod --output-hashing none
if [ $? -ne 0 ]; then
	echo "Project build failed"
        exit 2
fi

echo "Build succseeded."
